// ! log in
export const AUTH_LOGIN_FETCH = 'AUTH_LOGIN_FETCH';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

// ! Sign in
export const AUTH_SIGNIN_FETCH = 'AUTH_SIGNIN_FETCH';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

// ! Verify
export const VERIFY_ACCOUNT_FETCH = 'VERIFY_ACCOUNT_FETCH';
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS';
export const VERIFY_ACCOUNT_FAILURE = 'VERIFY_ACCOUNT_FAILURE';

// ! Change Password
export const CHANGE_PASSWORD_FETCH = 'CHANGE_PASSWORD_FETCH';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// ! Messages 
export const AUTH_MESSAGE = 'AUTH_MESSAGE';

