// !PATCH NAME
export const PATCH_NAME_FETCH = 'PATCH_NAME_FETCH';
export const PATCH_NAME_SUCCESS = 'PATCH_NAME_SUCCESS';
export const PATCH_NAME_FAILURE = 'PATCH_NAME_FAILURE';
// !PATCH CITY
export const PATCH_CITY_FETCH = 'PATH_CITY_FETCH';
export const PATCH_CITY_SUCCESS = 'PATH_CITY_SUCCESS';
export const PATCH_CITY_FAILURE = 'PATH_CITY_FAILURE';

// !PATCH PASSWORD 
export const PATCH_PASSWORD_FETCH = 'PATCH_PASSWORD_FETCH';
export const PATCH_PASSWORD_SUCCESS = 'PATH_CITY_SUCCESS';
export const PATCH_PASSWORD_FAILURE = 'PATH_CITY_FAILURE';

// ! Messages 
export const SETTINGS_MESSAGE = 'SETTINGS_MESSAGE';