// !  INOCME
export const GET_INCOME_FETCH = 'GET_INCOME_FETCH';
export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';
export const GET_INCOME_FAILURE = 'GET_INCOME_FAILURE';

export const POST_INCOME_FETCH = 'POST_INCOME_FETCH';
export const POST_INCOME_SUCCESS = 'POST_INCOME_SUCCESS';
export const POST_INCOME_FAILURE = 'POST_INCOME_FAILURE';

export const PUT_INCOME_FETCH = 'PUT_INCOME_FETCH';
export const PUT_INCOME_SUCCESS = 'PUT_INCOME_SUCCESS';
export const PUT_INCOME_FAILURE = 'PUT_INCOME_FAILURE';

export const DELETE_INCOME_FETCH = 'DELETE_INCOME_FETCH';
export const DELETE_INCOME_SUCCESS = 'DELETE_INCOME_SUCCESS';
export const DELETE_INCOME_FAILURE = 'DELETE_INCOME_FAILURE';

// ! EXPENSES
export const GET_EXPENSES_FETCH = 'GET_EXPENSES_FETCH';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAILURE = 'GET_EXPENSES_FAILURE';

export const POST_EXPENSES_FETCH = 'POST_EXPENSES_FETCH';
export const POST_EXPENSES_SUCCESS = 'POST_EXPENSES_SUCCESS';
export const POST_EXPENSES_FAILURE = 'POST_EXPENSES_FAILURE';

export const PUT_EXPENSES_FETCH = 'PUT_EXPENSES_FETCH';
export const PUT_EXPENSES_SUCCESS = 'PUT_EXPENSES_SUCCESS';
export const PUT_EXPENSES_FAILURE = 'PUT_EXPENSES_FAILURE';

export const DELETE_EXPENSES_FETCH = 'DELETE_EXPENSES_FETCH';
export const DELETE_EXPENSES_SUCCESS = 'DELETE_EXPENSES_SUCCESS';
export const DELETE_EXPENSES_FAILURE = 'DELETE_EXPENSES_FAILURE';

// ! Message 
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';